Algoritmo "exercicio_3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2023
Var
// Seção de Declarações das variáveis 
   i,num,quadrado :inteiro
Inicio


para i de 1 ate 64 faca
     quadrado<-num*2
     escreva(num%2)
fimpara

Fimalgoritmo