Algoritmo "repeticao"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2023
Var
// Seção de Declarações das variáveis 
   a :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <-1
   enquanto a<=5 faca
   escreval("Valor de a",a)
   a<-a+1
   fimenquanto

Fimalgoritmo